-- Migration 001: Add lecture_summaries table
-- Why: backend/db.py:153-186 references this table but pipeline/schema.sql does not declare it.
-- Fresh DB setup crashes on first /api/summaries/{lecture}/generate call.
-- Idempotent: safe to apply multiple times.

CREATE TABLE IF NOT EXISTS public.lecture_summaries (
    lecture        varchar(10)               PRIMARY KEY,
    lecture_title  text,
    summary        text                      NOT NULL,
    sources        jsonb                     DEFAULT '[]'::jsonb,
    generated_at   timestamp with time zone  DEFAULT now(),
    feedback       text,
    feedback_at    timestamp with time zone
);

CREATE INDEX IF NOT EXISTS idx_lecture_summaries_generated
    ON public.lecture_summaries (generated_at DESC);

COMMENT ON TABLE public.lecture_summaries IS
    'Cached lecture summaries generated by the Summary agent. Upserted on /api/summaries/{lecture}/generate.';
