#!/usr/bin/env python3
"""
generate_bank_v2.py — P7.2 bank expansion CLI (v0.5 Question Bank Pipeline).

Expands the question bank from 18 → 30+ PhD-rigor items by generating
cards for topics/types NOT yet covered in the existing bank.

Usage:
    python3 scripts/generate_bank_v2.py

Each generated item is:
  1. Retrieved from slides via RAG (/api/search).
  2. Generated by the QuestionGenerator agent.
  3. Inserted into question_bank table.
  4. Registered as srs_card for user_id=1.

Skips (topic, card_type, difficulty) combos already in the bank.
Prints a coverage matrix and sample items at the end.
"""
from __future__ import annotations

import asyncio
import json
import os
import sys
import time
from pathlib import Path
from typing import Optional

import requests  # sync HTTP for RAG search

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / "backend"))

# ──────────────────────────────────────────────────────────────────
# Expansion plan: 12 new items filling coverage gaps
# (topic, card_type, difficulty, bloom, slide_lecture, kw_search)
# ──────────────────────────────────────────────────────────────────

EXPANSION_PLAN = [
    # L4 synapses — totally missing from existing 18-item bank
    ("L4_synapses", "concept",     3, "Understand", "L4", "synaptic transmission ionotropic metabotropic"),
    ("L4_synapses", "application", 4, "Apply",      "L4", "EPSP IPSP NMDA AMPA"),
    ("L4_synapses", "proof",       4, "Analyze",    "L4", "synaptic conductance time course"),
    # L2 intro — missing
    ("L2_intro",    "concept",     3, "Understand", "L2", "computational neuroscience approaches levels"),
    ("L2_intro",    "application", 3, "Apply",      "L2", "RC circuit membrane equation passive neuron"),
    # L7 models — only model_types present (3 items); add specific lif/izhikevich
    ("L7_models",   "recall",      3, "Understand", "L7", "leaky integrate fire neuron threshold reset"),
    ("L7_models",   "concept",     4, "Analyze",    "L7", "Izhikevich Hodgkin-Huxley comparison conductance"),
    # L8 codes — only neural_codes (3 items, concept/application/proof); add recall
    ("L8_codes",    "recall",      2, "Remember",   "L8", "rate code temporal code phase code population"),
    ("L8_codes",    "application", 4, "Apply",      "L8", "tuning curve Fisher information neural coding"),
    # HH extra — voltage clamp protocol (not yet in bank at this type/diff)
    ("HH_extra",    "application", 4, "Apply",      "L5", "voltage clamp protocol leak subtraction HH"),
    # cable extra
    ("cable_extra", "application", 3, "Apply",      "L6", "axon diameter myelination conduction velocity"),
    # Nernst extra
    ("Nernst_extra","application", 4, "Apply",      "L3", "ion concentration physiological potassium chloride"),
]

BACKEND_URL = "http://127.0.0.1:8000"
DB_DSN = os.environ.get(
    "DATABASE_URL",
    "dbname=bri610 user=tutor password=tutor610 host=localhost",
)
USER_ID = 1


# ──────────────────────────────────────────────────────────────────
# DB helpers (sync psycopg2 — script context)
# ──────────────────────────────────────────────────────────────────

def _get_conn():
    import psycopg2
    return psycopg2.connect(DB_DSN)


def bank_count(conn) -> int:
    with conn.cursor() as cur:
        cur.execute("SELECT COUNT(*) FROM question_bank")
        return cur.fetchone()[0]


def existing_combos(conn) -> set[tuple]:
    """Return set of (topic, card_type, difficulty) already in the bank."""
    with conn.cursor() as cur:
        cur.execute("SELECT topic, card_type, difficulty FROM question_bank")
        return set(cur.fetchall())


def insert_bank_item(conn, item: dict, topic: str, card_type: str,
                     difficulty: int, bloom: str) -> Optional[int]:
    """Insert one item into question_bank; return new id or None on error."""
    cit = item.get("source_citation") or {}
    if not isinstance(cit, dict):
        cit = {}
    # Ensure kind = 'slide'
    cit.setdefault("kind", "slide")

    try:
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO question_bank
                  (topic, card_type, difficulty, bloom,
                   prompt_md, answer_md, rationale_md,
                   source_citation, priority_score, info_density,
                   mastery_target, status)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s::jsonb,%s,%s,%s,'active')
                RETURNING id
            """, (
                topic,
                card_type,
                difficulty,
                bloom,
                item.get("prompt_md", ""),
                item.get("answer_md", ""),
                item.get("rationale_md", ""),
                json.dumps(cit, ensure_ascii=False),
                0.75,   # default priority_score for generated items
                0.75,   # default info_density
                item.get("mastery_target", f"{topic}_{card_type}"),
            ))
            new_id = cur.fetchone()[0]
        conn.commit()
        return new_id
    except Exception as e:
        print(f"    [DB ERROR] insert_bank_item: {e}")
        try: conn.rollback()
        except Exception: pass
        return None


def register_srs_card(conn, bank_item_id: int, user_id: int = USER_ID) -> bool:
    """Register a new srs_card for the bank item (skip if already exists)."""
    try:
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO srs_cards (user_id, bank_item_id)
                VALUES (%s, %s)
                ON CONFLICT (user_id, bank_item_id) DO NOTHING
            """, (user_id, bank_item_id))
        conn.commit()
        return True
    except Exception as e:
        print(f"    [DB ERROR] register_srs_card: {e}")
        try: conn.rollback()
        except Exception: pass
        return False


# ──────────────────────────────────────────────────────────────────
# RAG search helper
# ──────────────────────────────────────────────────────────────────

def rag_search(query: str, lecture: str, limit: int = 6) -> tuple[str, list[dict]]:
    """
    Call /api/search with source=slides + lecture filter.
    Returns (context_text, slide_refs).
    Falls back to no lecture filter if no results found.
    """
    payload = {"query": query, "source": "slides", "lecture": lecture, "limit": limit}
    try:
        r = requests.post(f"{BACKEND_URL}/api/search", json=payload, timeout=30)
        r.raise_for_status()
        results = r.json()
    except Exception as e:
        print(f"    [RAG] Search failed with lecture={lecture}: {e}. Retrying without lecture filter...")
        # Retry without lecture filter
        try:
            payload2 = {"query": query, "source": "slides", "limit": limit}
            r2 = requests.post(f"{BACKEND_URL}/api/search", json=payload2, timeout=30)
            r2.raise_for_status()
            results = r2.json()
        except Exception as e2:
            print(f"    [RAG] Retry also failed: {e2}")
            return "", []

    if not results:
        # Try without lecture filter
        try:
            payload2 = {"query": query, "source": "slides", "limit": limit}
            r2 = requests.post(f"{BACKEND_URL}/api/search", json=payload2, timeout=30)
            r2.raise_for_status()
            results = r2.json()
        except Exception:
            pass

    if not results:
        return "", []

    # Build slide_refs whitelist from results
    slide_refs = []
    context_parts = []
    for hit in results:
        lec  = hit.get("lecture", "")
        page = hit.get("page", 0)
        title = hit.get("title", "")
        content = hit.get("content", "")
        slide_refs.append({"lecture": lec, "page": page, "title": title})
        context_parts.append(
            f"[{lec} p.{page} — {title}]\n{content[:600]}"
        )

    return "\n\n---\n\n".join(context_parts), slide_refs


# ──────────────────────────────────────────────────────────────────
# Coverage matrix printer
# ──────────────────────────────────────────────────────────────────

def print_coverage_matrix(conn) -> None:
    with conn.cursor() as cur:
        cur.execute("""
            SELECT topic, card_type, COUNT(*) as n
            FROM question_bank
            WHERE status = 'active'
            GROUP BY topic, card_type
            ORDER BY topic, card_type
        """)
        rows = cur.fetchall()

    # Build matrix
    topics = sorted(set(r[0] for r in rows))
    types  = ["recall", "concept", "application", "proof"]
    grid: dict[tuple, int] = {}
    for topic, ct, n in rows:
        grid[(topic, ct)] = n

    print("\n" + "="*70)
    print("COVERAGE MATRIX (topic × card_type)")
    print("="*70)
    header = f"{'topic':<20}" + "".join(f"{'  '+t:<16}" for t in types)
    print(header)
    print("-"*70)
    for topic in topics:
        row = f"{topic:<20}"
        for ct in types:
            n = grid.get((topic, ct), 0)
            cell = f"{'✓ '+str(n):<16}" if n else f"{'—':<16}"
            row += cell
        print(row)
    print("="*70)


def print_sample_items(conn, limit: int = 2) -> None:
    """Print the most recently inserted items."""
    with conn.cursor() as cur:
        cur.execute("""
            SELECT id, topic, card_type, difficulty, prompt_md, answer_md, source_citation
            FROM question_bank
            ORDER BY created_at DESC
            LIMIT %s
        """, (limit,))
        rows = cur.fetchall()

    print(f"\nSAMPLE {limit} NEWLY-GENERATED ITEMS")
    print("="*70)
    for row in rows:
        id_, topic, ct, diff, prompt, answer, cit = row
        print(f"\n[ID={id_}] topic={topic} type={ct} difficulty={diff}")
        print(f"source_citation: {cit}")
        print(f"PROMPT (first 200 chars): {prompt[:200]}...")
        print(f"ANSWER (first 200 chars): {answer[:200]}...")
        print("-"*60)


def check_non_slide_citations(conn) -> None:
    """Check for items where source_citation->>'kind' != 'slide'."""
    with conn.cursor() as cur:
        cur.execute("""
            SELECT COUNT(*), status
            FROM question_bank
            WHERE source_citation->>'kind' != 'slide'
            GROUP BY status
            ORDER BY status
        """)
        rows = cur.fetchall()

    total_non_slide = sum(r[0] for r in rows)
    print("\n" + "="*70)
    print("SMOKE TEST: Non-slide citations in bank")
    print("="*70)
    if total_non_slide == 0:
        print("  OK — all items have kind='slide' in source_citation.")
    else:
        print(f"  WARNING: {total_non_slide} item(s) have non-slide citations:")
        for count, status in rows:
            print(f"    status={status}: {count} item(s)")
        print("  (These may be pre-existing seed items — check their primary citations.)")
    print("="*70)


# ──────────────────────────────────────────────────────────────────
# Main async generation loop
# ──────────────────────────────────────────────────────────────────

async def run_expansion() -> None:
    from agents.question_generator import generate_question  # type: ignore[import]

    conn = _get_conn()
    t_start = time.perf_counter()

    # Pre-flight
    initial_count = bank_count(conn)
    print(f"\nBank size BEFORE: {initial_count} items")
    combos = existing_combos(conn)

    generated = 0
    rejected  = 0
    skipped   = 0
    new_ids   = []

    print(f"\nRunning {len(EXPANSION_PLAN)} expansion plan entries...\n")

    for idx, (topic, card_type, difficulty, bloom, lec, kw) in enumerate(EXPANSION_PLAN, 1):
        print(f"[{idx:02d}/{len(EXPANSION_PLAN)}] {topic} / {card_type} / diff={difficulty} / {bloom}")

        # Skip if (topic, card_type, difficulty) already in bank
        if (topic, card_type, difficulty) in combos:
            print(f"    -> SKIPPED (already exists in bank)")
            skipped += 1
            continue

        # RAG retrieval
        print(f"    -> RAG search: lecture={lec!r}, query={kw!r}")
        slide_context, slide_refs = rag_search(kw, lec, limit=6)
        if not slide_refs:
            print(f"    -> WARNING: No slide results. Generating with empty context.")

        # Generate
        t_item_start = time.perf_counter()
        item = await generate_question(
            topic=topic,
            card_type=card_type,
            difficulty=difficulty,
            bloom=bloom,
            slide_context=slide_context,
            slide_refs=slide_refs,
            mastery_target=f"{topic}_{card_type}",
        )
        elapsed_item = time.perf_counter() - t_item_start

        if item is None:
            print(f"    -> REJECTED (generation/parse failed after retry) [{elapsed_item:.1f}s]")
            rejected += 1
            continue

        # Insert into DB
        new_id = insert_bank_item(conn, item, topic, card_type, difficulty, bloom)
        if new_id is None:
            print(f"    -> REJECTED (DB insert failed) [{elapsed_item:.1f}s]")
            rejected += 1
            continue

        # Register SRS card
        register_srs_card(conn, new_id, USER_ID)
        combos.add((topic, card_type, difficulty))  # update local set
        new_ids.append(new_id)
        generated += 1
        cit = item.get("source_citation") or {}
        print(
            f"    -> OK (id={new_id}, cite={cit.get('lecture')} p.{cit.get('page')}) "
            f"[{elapsed_item:.1f}s]"
        )

    # ── Summary ────────────────────────────────────────────────────
    elapsed_total = time.perf_counter() - t_start
    final_count   = bank_count(conn)

    print("\n" + "="*70)
    print("GENERATION COMPLETE")
    print("="*70)
    print(f"  Wall-clock: {elapsed_total:.1f}s ({elapsed_total/60:.1f} min)")
    print(f"  Bank size BEFORE: {initial_count}")
    print(f"  Bank size AFTER:  {final_count}")
    print(f"  Generated (new):  {generated}")
    print(f"  Rejected:         {rejected}")
    print(f"  Skipped (dup):    {skipped}")

    print_coverage_matrix(conn)
    print_sample_items(conn, limit=2)
    check_non_slide_citations(conn)

    conn.close()


# ──────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    asyncio.run(run_expansion())
